name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         -  name: Checkout
            uses: actions/checkout@master

         -  name: Set Deployed Flag and Image Root
            run: |
               bash ./.github/set-deployed-flag.sh ${{ github.ref_name }}
               bash ./.github/set-img-root.sh

         # Notably: remove anything which should not be added to the service worker manifest:
         #  - `homebrew`
         #  - `prerelease`
         -  name: Cleanup
            run: |
               rm -rf *.md *.zip scss spellcheck homebrew prerelease
               ls -lah

         # Remove entries from the `.gitignore` so the gh-pages action can correctly add+commit them to the pages branch
         -  name: Build Service Worker
            run: |
               node --version
               npm --version
               npm i
               npm run build:sw:prod
               sed -i 's/sw.js//g' .gitignore
               sed -i 's/sw-injector.js//g' .gitignore

         -  name: Build SEO Pages
            env:
               VET_SEO_IS_DEV_MODE: true
               VET_BASE_SITE_URL: https://5etools-mirror-2.github.io/
               VET_SEO_IS_SKIP_UA_ETC: true
            run: |
               npm run build:seo -- ${{ github.ref_name }}

         -  name: Cleanup
            run: |
               rm -rf node_modules node
               ls -lah

         -  name: Setup Pages
            uses: actions/configure-pages@master

         -  name: Upload artifact
            uses: actions/upload-pages-artifact@master
            with:
               path: '.'

         - name: Sync to Gitee
           uses: wearerequired/git-mirror-action@master
           env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
               SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
           with:
          # 注意替换为你的 GitHub 源仓库地址
               source-repo: git@github.com:monthwolf/5etools-zh.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
               destination-repo: git@gitee.com:monthwolf/5etools-zh.git

         - name: Build Gitee Pages
           uses: yanglbme/gitee-pages-action@main
           with:
          # 注意替换为你的 Gitee 用户名
             gitee-username: monthwolf
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
             gitee-password: 59aac15ab543a63afe469cfc013d8dd2
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
             gitee-repo: monthwolf/5etools-zh
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
             branch: main
