name: translate

env:
  SOURCE_FILES: 'data/spells/*.json data/class/*.json data/*.json data/book/*.json data/adventure/*.json data/bestiary/*.json'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source files'
        required: True
        default: ${SOURCE_FILES}
  schedule:
    - cron: "10 5 * * *"

concurrency:
  group: "translation"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'translations'
        fetch-depth: 0
    - name: Merge latest upstream
      continue-on-error: true
      run: |
           git remote add upstream https://github.com/5etools-mirror-2/5etools-mirror-2.github.io
           git fetch upstream
           git config user.name "Automatic translator"
           git config user.email "<>"
           git merge upstream/master
           git push
  translate:
    needs: merge-upstream
    strategy:
      max-parallel: 1
      matrix:
        language: ['zh']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'translations'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Set up dependencies
      run: |
           #sudo apt-get install -y firefox
           pip3 install selenium webdriver_manager
    - name: Generate translations
      continue-on-error: true
      run: |
           cd $GITHUB_WORKSPACE
           ./translation/translate.py --language ${{ matrix.language }} --maxrun 18000 --translate --deepl $SOURCE_FILES
           ./translation/translate.py --language ${{ matrix.language }} --translate data/*.json data/*/*.json
           tail -n 1000 geckodriver.log
           mv data data.src
           ln -s data.${{ matrix.language }} data
           npm run gen
           rm -f data
           mv data.src data
    - name: Save results
      continue-on-error: true
      run: |
           git config user.name "Automatic translator"
           git config user.email "<>"
           git add data.${{ matrix.language }}/ translation/cache/${{ matrix.language }}/
           git commit -m 'automatic translation'
           git status
           git checkout HEAD .
           git pull --rebase --autostash
           git push origin translations || true
           # Try again with a short delay in case it fails (conflicting pushes)
           sleep $((1 + $RANDOM % 10 * 10))
           git pull --rebase --autostash
           git push origin translations || true
           #sleep $((1 + $RANDOM % 10 * 10))
           #git pull --rebase --autostash
           #git push origin translations || true
           #sleep $((1 + $RANDOM % 10 * 10))
           #git pull --rebase --autostash
           #git push origin translations || true
  deploy:
    needs: translate
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
       - uses: actions/checkout@master
         with:
           ref: 'translations'
           fetch-depth: 0 # So we get the last official release tag

       - name: cache buster
         run: |
              cd $GITHUB_WORKSPACE
              VERSION=$(git describe --tags --abbrev=0)
              bash ./.github/set-deployed-flag.sh "${VERSION}.$(date +%s)"

       - name: Build Service Worker
         run: |
              npm i
              npm run build:sw:prod
              sed -i 's/sw.js//g' .gitignore
              sed -i 's/sw-injector.js//g' .gitignore

       - name: cleanup
         run: |
              # Clean unnecessary files for pages deploy
              rm -rf translation
              rm -rf node_modules

       -  name: Setup Pages
          uses: actions/configure-pages@master

       -  name: Upload artifact
          uses: actions/upload-pages-artifact@master
          with:
             path: '.'

       -  name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@master
          with:
             # Timeout in millis (2 hour)
             timeout: 7200000
