name: upstream

on:
  schedule:
    - cron: "00 5 * * *"
  workflow_dispatch:
concurrency:
  group: "translation"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    merge-upstream:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          with:
                ref: 'translations'
                fetch-depth: 0
        - name: Merge latest upstream
          continue-on-error: true
          run: |
                cd $GITHUB_WORKSPACE
                mv data data.zh
                rm -rf data.en
                git config user.name "Automatic translator"
                git config user.email "<>"
                unzip data.zip
                mv data data.en
                mv data.zh data
                git commit -a
                git push
